/**
 **************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 **************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 **************************************************************************
 */

#include "stm32f401re_gpio.h"
#include "stm32f401re_rcc.h"

#define GPIO_PIN_SET 1
#define GPIO_PIN_RESET 0
#define GPIO_PIN_LOW 1
#define GPIO_PIN_HIGH 0

#define BUZZER_GPIO_PORT GPIOC
#define BUZZER_GPIO_PIN GPIO_Pin_9
#define BUZZER_PIN9 9
#define BUZZERControl_SetClock RCC_AHB1Periph_GPIOC

#define BUTTON_GPIO_PORT GPIOB
#define BUTTON_GPIO_PIN GPIO_Pin_4
#define BUTTON_B2 4
#define BUTTONControl_SetClock RCC_AHB1Periph_GPIOB

static void Buzzer_Init(void)
{
    GPIO_InitTypeDef GPIO_InitStructure;
    RCC_AHB1PeriphClockCmd(BUZZERControl_SetClock, ENABLE);
    GPIO_InitStructure.GPIO_Pin = BUZZER_GPIO_PIN;
    GPIO_InitStructure.GPIO_Mode = GPIO_Mode_OUT;
    GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
    GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;
    GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_DOWN;
    GPIO_Init(BUZZER_GPIO_PORT, &GPIO_InitStructure);
}

static void Button_Init(void)
{
    GPIO_InitTypeDef GPIO_InitStructure;
    RCC_AHB1PeriphClockCmd(BUTTONControl_SetClock, ENABLE);
    GPIO_InitStructure.GPIO_Pin = BUTTON_GPIO_PIN;
    GPIO_InitStructure.GPIO_Mode = GPIO_Mode_IN;
    GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
    GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_UP;
    GPIO_Init(BUTTON_GPIO_PORT, &GPIO_InitStructure);
}

static uint8_t ButtonRead_Status(GPIO_TypeDef *GPIOx, uint32_t GPIO_PIN)
{
    uint32_t Read_Pin;

    Read_Pin = (GPIOx->IDR) >> GPIO_PIN;
    Read_Pin = Read_Pin & 0x01;

    return Read_Pin;
}

static void BuzzerControl_SetStatus(GPIO_TypeDef *GPIOx, uint8_t GPIO_PIN, uint8_t Status)
{
    if (Status == GPIO_PIN_SET)
    {
        GPIOx->BSRRL |= 1 << GPIO_PIN;
    }
    if (Status == GPIO_PIN_RESET)
    {
        GPIOx->BSRRH |= 1 << GPIO_PIN;
    }
}

static void Buzzer_Toggle(GPIO_TypeDef *GPIOx, uint8_t GPIO_PIN)
{
    if(GPIOx->ODR & (1 << GPIO_PIN))
    {
        BuzzerControl_SetStatus(GPIOx, GPIO_PIN, GPIO_PIN_RESET);
    }
    else
    {
        BuzzerControl_SetStatus(GPIOx, GPIO_PIN, GPIO_PIN_SET);
    }
}

int main(void)
{
    uint8_t buttonState = 1;      // Current button state
    uint8_t lastButtonState = 1;  // Previous button state
    uint8_t buzzerState = 0;      // Current buzzer state

    Buzzer_Init();
    Button_Init();

    // Initial state - buzzer off
    BuzzerControl_SetStatus(BUZZER_GPIO_PORT, BUZZER_PIN9, GPIO_PIN_RESET);
    while (1)
        {
            // Read the button state
            buttonState = ButtonRead_Status(BUTTON_GPIO_PORT, BUTTON_B2);

            // Check for button press (falling edge)
            if (buttonState == 0 && lastButtonState == 1)
            {
                // Toggle the buzzer state
                Buzzer_Toggle(BUZZER_GPIO_PORT, BUZZER_PIN9);

                // Simple debounce delay
                for(volatile uint32_t i = 0; i < 100000; i++);
            }

            // Update the last button state
            lastButtonState = buttonState;
        }
    }
